//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     Version: 1.3300.16.0
//
//     Project:     Standard_Classroom
//     Version:     1.0.0.0
//     Sdk:         CH5:2.8.0
//     Strategy:    Classic
//     IndexOnly:   False
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Crestron.SimplSharpPro.DeviceSupport;
using Crestron.SimplSharpPro;
using Standard_Classroom;

namespace Standard_Classroom.Main_Page.Volume_Control_0x_Panel_Widget
{

    /// <summary>
    /// Allow click events by item
    /// </summary>
    public partial interface IListMicSelectionByItem
    {
        /// <summary>
        /// Fires on button list presses.  Event carries <see="IndexedButtonEventArgs"/> with ButtonIndex property (0 based).
        /// </summary>
        event EventHandler<IndexedButtonEventArgs> Button_PressEvent;

        /// <summary>
        /// Main_Page.Volume_Control_0x_Panel_Widget.Button1.ItemSelected Feedback
        /// </summary>
        /// <param name="buttonIndex">The index of the button (0 based).</param>
        /// <param name="callback">The delegate to set the feedback.</param>
        void Button_Selected(ushort buttonIndex, ListMicSelectionBoolInputSigDelegate callback);

        /// <summary>
        /// Helper Main_Page.Volume_Control_0x_Panel_Widget.Button1.ItemSelected Feedback
        /// </summary>
        /// <param name="buttonIndex">The index of the button (0 based).</param>
        /// <param name="digital">The <see="bool"/> value to set on the panel.</param>
        void Button_Selected(ushort buttonIndex, bool digital);

        /// <summary>
        /// Main_Page.Volume_Control_0x_Panel_Widget.Button1.Visible Feedback
        /// </summary>
        /// <param name="buttonIndex">The index of the button (0 based).</param>
        /// <param name="callback">The delegate to set the feedback.</param>
        void Button_Visible(ushort buttonIndex, ListMicSelectionBoolInputSigDelegate callback);

        /// <summary>
        /// Helper Main_Page.Volume_Control_0x_Panel_Widget.Button1.Visible Feedback
        /// </summary>
        /// <param name="buttonIndex">The index of the button (0 based).</param>
        /// <param name="digital">The <see="bool"/> value to set on the panel.</param>
        void Button_Visible(ushort buttonIndex, bool digital);
    }


    /// <summary>
    /// Search List
    /// </summary>
    internal partial class ListMicSelection
    {
        #region CH5 Contract

        public event EventHandler<IndexedButtonEventArgs> Button_PressEvent;
        private void onButton_Press(IndexedEventArgs eventArgs)
        {
            EventHandler<IndexedButtonEventArgs> handler = Button_PressEvent;
            if (handler != null)
                handler(this, new IndexedButtonEventArgs((SmartObjectEventArgs)eventArgs.SigArgs, eventArgs.JoinIndex));
        }
                
        /// <summary>
        /// Boolean feedbacks (from Control System to Panel)
        /// </summary>
        /// <param name="buttonIndex">The index of the button (0 based).</param>
        /// <param name="callback">The delegate to set the feedback.</param>
        public void Button_Visible(ushort buttonIndex, ListMicSelectionBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Button_1_Button_VisibleState + buttonIndex], this);
            }
        }

        /// <summary>
        /// Set Boolean feedback (from Control System to Panel)
        /// </summary>
        /// <param name="buttonIndex">The index of the button (0 based).</param>
        /// <param name="digital">The bool value to set.</param>
        public void Button_Visible(ushort buttonIndex, bool digital)
        {
            Button_Visible(buttonIndex, (sig, component) => sig.BoolValue = digital);
        }
        /// <summary>
        /// Boolean feedbacks (from Control System to Panel)
        /// </summary>
        /// <param name="buttonIndex">The index of the button (0 based).</param>
        /// <param name="callback">The delegate to set the feedback.</param>
        public void Button_Selected(ushort buttonIndex, ListMicSelectionBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Button_1_Button_SelectedState + buttonIndex], this);
            }
        }

        /// <summary>
        /// Set Boolean feedback (from Control System to Panel)
        /// </summary>
        /// <param name="buttonIndex">The index of the button (0 based).</param>
        /// <param name="digital">The bool value to set.</param>
        public void Button_Selected(ushort buttonIndex, bool digital)
        {
            Button_Selected(buttonIndex, (sig, component) => sig.BoolValue = digital);
        }

        #endregion
    }

    /// <summary>
    /// List.MicSelection
    /// </summary>
    public partial interface IListMicSelection : IListMicSelectionByItem
    {
        object UserObject { get; set; }

        /// <summary>
        /// Main_Page.Volume_Control_0x_Panel_Widget.Button1.ItemPress
        /// </summary>
        event EventHandler<UIEventArgs> Button_1_Button_PressEvent;

        /// <summary>
        /// Main_Page.Volume_Control_0x_Panel_Widget.Button2.ItemPress
        /// </summary>
        event EventHandler<UIEventArgs> Button_2_Button_PressEvent;

        /// <summary>
        /// Main_Page.Volume_Control_0x_Panel_Widget.Button3.ItemPress
        /// </summary>
        event EventHandler<UIEventArgs> Button_3_Button_PressEvent;

        /// <summary>
        /// Main_Page.Volume_Control_0x_Panel_Widget.Button4.ItemPress
        /// </summary>
        event EventHandler<UIEventArgs> Button_4_Button_PressEvent;

        /// <summary>
        /// Main_Page.Volume_Control_0x_Panel_Widget.Button1.ItemSelected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Button_1_Button_Selected(ListMicSelectionBoolInputSigDelegate callback);

        /// <summary>
        /// Main_Page.Volume_Control_0x_Panel_Widget.Button1.ItemSelected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Button_1_Button_Selected(bool digital);

        /// <summary>
        /// Main_Page.Volume_Control_0x_Panel_Widget.Button2.ItemSelected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Button_2_Button_Selected(ListMicSelectionBoolInputSigDelegate callback);

        /// <summary>
        /// Main_Page.Volume_Control_0x_Panel_Widget.Button2.ItemSelected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Button_2_Button_Selected(bool digital);

        /// <summary>
        /// Main_Page.Volume_Control_0x_Panel_Widget.Button3.ItemSelected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Button_3_Button_Selected(ListMicSelectionBoolInputSigDelegate callback);

        /// <summary>
        /// Main_Page.Volume_Control_0x_Panel_Widget.Button3.ItemSelected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Button_3_Button_Selected(bool digital);

        /// <summary>
        /// Main_Page.Volume_Control_0x_Panel_Widget.Button4.ItemSelected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Button_4_Button_Selected(ListMicSelectionBoolInputSigDelegate callback);

        /// <summary>
        /// Main_Page.Volume_Control_0x_Panel_Widget.Button4.ItemSelected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Button_4_Button_Selected(bool digital);

        /// <summary>
        /// Main_Page.Volume_Control_0x_Panel_Widget.Button1.Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Button_1_Button_Visible(ListMicSelectionBoolInputSigDelegate callback);

        /// <summary>
        /// Main_Page.Volume_Control_0x_Panel_Widget.Button1.Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Button_1_Button_Visible(bool digital);

        /// <summary>
        /// Main_Page.Volume_Control_0x_Panel_Widget.Button2.Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Button_2_Button_Visible(ListMicSelectionBoolInputSigDelegate callback);

        /// <summary>
        /// Main_Page.Volume_Control_0x_Panel_Widget.Button2.Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Button_2_Button_Visible(bool digital);

        /// <summary>
        /// Main_Page.Volume_Control_0x_Panel_Widget.Button3.Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Button_3_Button_Visible(ListMicSelectionBoolInputSigDelegate callback);

        /// <summary>
        /// Main_Page.Volume_Control_0x_Panel_Widget.Button3.Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Button_3_Button_Visible(bool digital);

        /// <summary>
        /// Main_Page.Volume_Control_0x_Panel_Widget.Button4.Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Button_4_Button_Visible(ListMicSelectionBoolInputSigDelegate callback);

        /// <summary>
        /// Main_Page.Volume_Control_0x_Panel_Widget.Button4.Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Button_4_Button_Visible(bool digital);
    }

    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="boolInputSig">The <see cref="BoolInputSig"/> signal data.</param>
    /// <param name="listmicselection">The <see cref="IListMicSelection"/> on which to apply the feedback.</param>
    public delegate void ListMicSelectionBoolInputSigDelegate(BoolInputSig boolInputSig, IListMicSelection listmicselection);

    /// <summary>
    /// List.MicSelection
    /// </summary>
    internal partial class ListMicSelection : IListMicSelection, IDisposable
    {
        #region Standard CH5 Component members

        private ComponentMediator ComponentMediator { get; set; }

        public object UserObject { get; set; }

        /// <summary>
        /// Gets the ControlJoinId a.k.a. SmartObjectId.  This Id identifies the extender symbol.
        /// </summary>
        public uint ControlJoinId { get; private set; }

        private IList<BasicTriListWithSmartObject> _devices;

        /// <summary>
        /// Gets the list of devices.
        /// </summary>
        public IList<BasicTriListWithSmartObject> Devices { get { return _devices; } }

        #endregion

        #region Joins

        private static class Joins
        {
            /// <summary>
            /// Digital signals,
            /// </summary>
            internal static class Booleans
            {
                /// <summary>
                /// Output or Event digital signal from panel to Control System: Main_Page.Volume_Control_0x_Panel_Widget.ListMicSelection.Button1ItemPress
                /// Main_Page.Volume_Control_0x_Panel_Widget.Button1.ItemPress
                /// </summary>
                public const uint Button_1_Button_PressEvent = 1001;

                /// <summary>
                /// Output or Event digital signal from panel to Control System: Main_Page.Volume_Control_0x_Panel_Widget.ListMicSelection.Button2ItemPress
                /// Main_Page.Volume_Control_0x_Panel_Widget.Button2.ItemPress
                /// </summary>
                public const uint Button_2_Button_PressEvent = 1002;

                /// <summary>
                /// Output or Event digital signal from panel to Control System: Main_Page.Volume_Control_0x_Panel_Widget.ListMicSelection.Button3ItemPress
                /// Main_Page.Volume_Control_0x_Panel_Widget.Button3.ItemPress
                /// </summary>
                public const uint Button_3_Button_PressEvent = 1003;

                /// <summary>
                /// Output or Event digital signal from panel to Control System: Main_Page.Volume_Control_0x_Panel_Widget.ListMicSelection.Button4ItemPress
                /// Main_Page.Volume_Control_0x_Panel_Widget.Button4.ItemPress
                /// </summary>
                public const uint Button_4_Button_PressEvent = 1004;


                /// <summary>
                /// Input or Feedback digital signal from Control System to panel: Main_Page.Volume_Control_0x_Panel_Widget.ListMicSelection.Button1ItemSelected
                /// Main_Page.Volume_Control_0x_Panel_Widget.Button1.ItemSelected
                /// </summary>
                public const uint Button_1_Button_SelectedState = 1001;

                /// <summary>
                /// Input or Feedback digital signal from Control System to panel: Main_Page.Volume_Control_0x_Panel_Widget.ListMicSelection.Button2ItemSelected
                /// Main_Page.Volume_Control_0x_Panel_Widget.Button2.ItemSelected
                /// </summary>
                public const uint Button_2_Button_SelectedState = 1002;

                /// <summary>
                /// Input or Feedback digital signal from Control System to panel: Main_Page.Volume_Control_0x_Panel_Widget.ListMicSelection.Button3ItemSelected
                /// Main_Page.Volume_Control_0x_Panel_Widget.Button3.ItemSelected
                /// </summary>
                public const uint Button_3_Button_SelectedState = 1003;

                /// <summary>
                /// Input or Feedback digital signal from Control System to panel: Main_Page.Volume_Control_0x_Panel_Widget.ListMicSelection.Button4ItemSelected
                /// Main_Page.Volume_Control_0x_Panel_Widget.Button4.ItemSelected
                /// </summary>
                public const uint Button_4_Button_SelectedState = 1004;

                /// <summary>
                /// Input or Feedback digital signal from Control System to panel: Main_Page.Volume_Control_0x_Panel_Widget.ListMicSelection.Button1Visible
                /// Main_Page.Volume_Control_0x_Panel_Widget.Button1.Visible
                /// </summary>
                public const uint Button_1_Button_VisibleState = 1501;

                /// <summary>
                /// Input or Feedback digital signal from Control System to panel: Main_Page.Volume_Control_0x_Panel_Widget.ListMicSelection.Button2Visible
                /// Main_Page.Volume_Control_0x_Panel_Widget.Button2.Visible
                /// </summary>
                public const uint Button_2_Button_VisibleState = 1502;

                /// <summary>
                /// Input or Feedback digital signal from Control System to panel: Main_Page.Volume_Control_0x_Panel_Widget.ListMicSelection.Button3Visible
                /// Main_Page.Volume_Control_0x_Panel_Widget.Button3.Visible
                /// </summary>
                public const uint Button_3_Button_VisibleState = 1503;

                /// <summary>
                /// Input or Feedback digital signal from Control System to panel: Main_Page.Volume_Control_0x_Panel_Widget.ListMicSelection.Button4Visible
                /// Main_Page.Volume_Control_0x_Panel_Widget.Button4.Visible
                /// </summary>
                public const uint Button_4_Button_VisibleState = 1504;

            }
        }

        #endregion

        #region Construction and Initialization

        /// <summary>
        /// Initializes a new instance of the <see cref="ListMicSelection"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        internal ListMicSelection(ComponentMediator componentMediator, uint controlJoinId, uint? itemCount)
        {
            ComponentMediator = componentMediator;
            Initialize(controlJoinId, itemCount);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ListMicSelection"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        internal ListMicSelection(ComponentMediator componentMediator, uint controlJoinId) : this(componentMediator, controlJoinId, null)
        {
        }

        /// <summary>
        /// Initializes a new instance with default itemCount.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        private void Initialize(uint controlJoinId)
        {
            Initialize(controlJoinId, null);
        }

        private Dictionary<string, Indexes> _indexLookup = new Dictionary<string, Indexes>();

        /// <summary>
        /// Initializes a new instance of the <see cref="ListMicSelection"/> component class.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        private void Initialize(uint controlJoinId, uint? itemCount)
        {
            ControlJoinId = controlJoinId; 
 
            _devices = new List<BasicTriListWithSmartObject>(); 
 

            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.Button_1_Button_PressEvent, onButton_1_Button_Press);
            ComponentMediator.ConfigureBooleanItemEvent(controlJoinId, Joins.Booleans.Button_1_Button_PressEvent, GetIndexes, onButton_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.Button_2_Button_PressEvent, onButton_2_Button_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.Button_3_Button_PressEvent, onButton_3_Button_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.Button_4_Button_PressEvent, onButton_4_Button_Press);
        }

        /// <summary>
        /// Get the offset when using indexed complex components.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId of the component.</param>
        /// <param name="join">The join offset.</param>
        /// <param name="eSigType">The join data type.</param>
        private Indexes GetIndexes(uint controlJoinId, uint join, eSigType eSigType)
        {
            if (controlJoinId == ControlJoinId &&
                join >= Joins.Booleans.Button_1_Button_PressEvent &&
                join <= 1004)
            {
                return new Indexes(0, (ushort)(join - Joins.Booleans.Button_1_Button_PressEvent), false);
            }

            return new Indexes(0, 0, true);
        }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            Devices.Add(device);
            ComponentMediator.HookSmartObjectEvents(device.SmartObjects[ControlJoinId]);
        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            Devices.Remove(device);
            ComponentMediator.UnHookSmartObjectEvents(device.SmartObjects[ControlJoinId]);
        }

        #endregion

        #region CH5 Contract

        /// <summary>
        /// Event Main_Page.Volume_Control_0x_Panel_Widget.Button1.ItemPress (from panel to Control System)
        /// </summary>
        public event EventHandler<UIEventArgs> Button_1_Button_PressEvent;
        private void onButton_1_Button_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = Button_1_Button_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <summary>
        /// Event Main_Page.Volume_Control_0x_Panel_Widget.Button2.ItemPress (from panel to Control System)
        /// </summary>
        public event EventHandler<UIEventArgs> Button_2_Button_PressEvent;
        private void onButton_2_Button_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = Button_2_Button_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <summary>
        /// Event Main_Page.Volume_Control_0x_Panel_Widget.Button3.ItemPress (from panel to Control System)
        /// </summary>
        public event EventHandler<UIEventArgs> Button_3_Button_PressEvent;
        private void onButton_3_Button_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = Button_3_Button_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <summary>
        /// Event Main_Page.Volume_Control_0x_Panel_Widget.Button4.ItemPress (from panel to Control System)
        /// </summary>
        public event EventHandler<UIEventArgs> Button_4_Button_PressEvent;
        private void onButton_4_Button_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = Button_4_Button_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <summary>
        /// Boolean feedback Main_Page.Volume_Control_0x_Panel_Widget.Button1.ItemSelected (from Control System to Panel)
        /// </summary>
        public void Button_1_Button_Selected(ListMicSelectionBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Button_1_Button_SelectedState], this);
            }
        }

        /// <summary>
        /// Boolean feedback Main_Page.Volume_Control_0x_Panel_Widget.Button1.ItemSelected (from Control System to Panel)
        /// </summary>
        public void Button_1_Button_Selected(bool digital)
        {
            Button_1_Button_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <summary>
        /// Boolean feedback Main_Page.Volume_Control_0x_Panel_Widget.Button1.Visible (from Control System to Panel)
        /// </summary>
        public void Button_1_Button_Visible(ListMicSelectionBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Button_1_Button_VisibleState], this);
            }
        }

        /// <summary>
        /// Boolean feedback Main_Page.Volume_Control_0x_Panel_Widget.Button1.Visible (from Control System to Panel)
        /// </summary>
        public void Button_1_Button_Visible(bool digital)
        {
            Button_1_Button_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <summary>
        /// Boolean feedback Main_Page.Volume_Control_0x_Panel_Widget.Button2.ItemSelected (from Control System to Panel)
        /// </summary>
        public void Button_2_Button_Selected(ListMicSelectionBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Button_2_Button_SelectedState], this);
            }
        }

        /// <summary>
        /// Boolean feedback Main_Page.Volume_Control_0x_Panel_Widget.Button2.ItemSelected (from Control System to Panel)
        /// </summary>
        public void Button_2_Button_Selected(bool digital)
        {
            Button_2_Button_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <summary>
        /// Boolean feedback Main_Page.Volume_Control_0x_Panel_Widget.Button2.Visible (from Control System to Panel)
        /// </summary>
        public void Button_2_Button_Visible(ListMicSelectionBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Button_2_Button_VisibleState], this);
            }
        }

        /// <summary>
        /// Boolean feedback Main_Page.Volume_Control_0x_Panel_Widget.Button2.Visible (from Control System to Panel)
        /// </summary>
        public void Button_2_Button_Visible(bool digital)
        {
            Button_2_Button_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <summary>
        /// Boolean feedback Main_Page.Volume_Control_0x_Panel_Widget.Button3.ItemSelected (from Control System to Panel)
        /// </summary>
        public void Button_3_Button_Selected(ListMicSelectionBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Button_3_Button_SelectedState], this);
            }
        }

        /// <summary>
        /// Boolean feedback Main_Page.Volume_Control_0x_Panel_Widget.Button3.ItemSelected (from Control System to Panel)
        /// </summary>
        public void Button_3_Button_Selected(bool digital)
        {
            Button_3_Button_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <summary>
        /// Boolean feedback Main_Page.Volume_Control_0x_Panel_Widget.Button3.Visible (from Control System to Panel)
        /// </summary>
        public void Button_3_Button_Visible(ListMicSelectionBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Button_3_Button_VisibleState], this);
            }
        }

        /// <summary>
        /// Boolean feedback Main_Page.Volume_Control_0x_Panel_Widget.Button3.Visible (from Control System to Panel)
        /// </summary>
        public void Button_3_Button_Visible(bool digital)
        {
            Button_3_Button_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <summary>
        /// Boolean feedback Main_Page.Volume_Control_0x_Panel_Widget.Button4.ItemSelected (from Control System to Panel)
        /// </summary>
        public void Button_4_Button_Selected(ListMicSelectionBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Button_4_Button_SelectedState], this);
            }
        }

        /// <summary>
        /// Boolean feedback Main_Page.Volume_Control_0x_Panel_Widget.Button4.ItemSelected (from Control System to Panel)
        /// </summary>
        public void Button_4_Button_Selected(bool digital)
        {
            Button_4_Button_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <summary>
        /// Boolean feedback Main_Page.Volume_Control_0x_Panel_Widget.Button4.Visible (from Control System to Panel)
        /// </summary>
        public void Button_4_Button_Visible(ListMicSelectionBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Button_4_Button_VisibleState], this);
            }
        }

        /// <summary>
        /// Boolean feedback Main_Page.Volume_Control_0x_Panel_Widget.Button4.Visible (from Control System to Panel)
        /// </summary>
        public void Button_4_Button_Visible(bool digital)
        {
            Button_4_Button_Visible((sig, component) => sig.BoolValue = digital);
        }

        #endregion

        #region Overrides

        public override int GetHashCode()
        {
            return (int)ControlJoinId;
        }

        public override string ToString()
        {
            return string.Format("Contract: {0} Component: {1} HashCode: {2} {3}", "ListMicSelection", GetType().Name, GetHashCode(), UserObject != null ? "UserObject: " + UserObject : null);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

            Button_1_Button_PressEvent = null;
            Button_PressEvent = null;
            Button_2_Button_PressEvent = null;
            Button_3_Button_PressEvent = null;
            Button_4_Button_PressEvent = null;
        }

        #endregion
    }
}
