//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     Version: 1.3501.16.0
//
//     Project:     The_Campfire_Theatre
//     Version:     1.0.0.0
//     Sdk:         CH5:2.11.1
//     Strategy:    Classic
//     IndexOnly:   True
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using The_Campfire_Theatre;

namespace The_Campfire_Theatre
{

    /// <summary>
    /// VidWall_Control_Widget
    /// </summary>
    public partial interface IVidWall_Control_Widget 
    {
        object UserObject { get; set; }

        /// <summary>
        /// Event Btn.Win[1]_FreezeTgl.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> BtnWin_1__FreezeTgl_PressEvent;

        /// <summary>
        /// Event Btn.Win[1]_ImageMuteTgl.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> BtnWin_1__ImageMuteTgl_PressEvent;

        /// <summary>
        /// Event Button_1.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> Button_1_PressEvent;

        /// <summary>
        /// Event Button.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> Button_PressEvent;

        /// <summary>
        /// Btn.Win[1]_FreezeTgl.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void BtnWin_1__FreezeTgl_Selected(VidWall_Control_WidgetBoolInputSigDelegate callback);

        /// <summary>
        /// Btn.Win[1]_FreezeTgl.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void BtnWin_1__FreezeTgl_Selected(bool digital);

        /// <summary>
        /// Btn.Win[1]_ImageMuteTgl.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void BtnWin_1__ImageMuteTgl_Selected(VidWall_Control_WidgetBoolInputSigDelegate callback);

        /// <summary>
        /// Btn.Win[1]_ImageMuteTgl.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void BtnWin_1__ImageMuteTgl_Selected(bool digital);

        /// <summary>
        /// Button_1.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Button_1_Selected(VidWall_Control_WidgetBoolInputSigDelegate callback);

        /// <summary>
        /// Button_1.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Button_1_Selected(bool digital);

        /// <summary>
        /// Button.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Button_Selected(VidWall_Control_WidgetBoolInputSigDelegate callback);

        /// <summary>
        /// Button.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Button_Selected(bool digital);
    }

    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="boolInputSig">The <see cref="BoolInputSig"/> joinInfo data.</param>
    /// <param name="vidwall_control_widget">The <see cref="IVidWall_Control_Widget"/> on which to apply the feedback.</param>
    public delegate void VidWall_Control_WidgetBoolInputSigDelegate(BoolInputSig boolInputSig, IVidWall_Control_Widget vidwall_control_widget);

    /// <summary>
    /// VidWall_Control_Widget
    /// </summary>
    internal partial class VidWall_Control_Widget : IVidWall_Control_Widget, IDisposable
    {
        #region Standard CH5 Component members

        private ComponentMediator ComponentMediator { get; set; }

        public object UserObject { get; set; }

        /// <summary>
        /// Gets the ControlJoinId a.k.a. SmartObjectId.  This Id identifies the extender symbol.
        /// </summary>
        public uint ControlJoinId { get; private set; }

        private IList<BasicTriListWithSmartObject> _devices;

        /// <summary>
        /// Gets the list of devices.
        /// </summary>
        public IList<BasicTriListWithSmartObject> Devices { get { return _devices; } }

        #endregion

        #region Joins

        private static class Joins
        {
            /// <summary>
            /// Digital signals,
            /// </summary>
            internal static class Booleans
            {
                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: VidWall_Control_Widget.BtnWin[1]_FreezeTgl.Press
                /// Btn.Win[1]_FreezeTgl.Press
                /// </summary>
                public const uint BtnWin_1__FreezeTgl_PressEvent = 3;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: VidWall_Control_Widget.BtnWin[1]_ImageMuteTgl.Press
                /// Btn.Win[1]_ImageMuteTgl.Press
                /// </summary>
                public const uint BtnWin_1__ImageMuteTgl_PressEvent = 4;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: VidWall_Control_Widget.Button_1.Press
                /// Button_1.Press
                /// </summary>
                public const uint Button_1_PressEvent = 5;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: VidWall_Control_Widget.Button.Press
                /// Button.Press
                /// </summary>
                public const uint Button_PressEvent = 6;


                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: VidWall_Control_Widget.BtnWin[1]_FreezeTgl.Selected
                /// Btn.Win[1]_FreezeTgl.Selected
                /// </summary>
                public const uint BtnWin_1__FreezeTgl_SelectedState = 3;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: VidWall_Control_Widget.BtnWin[1]_ImageMuteTgl.Selected
                /// Btn.Win[1]_ImageMuteTgl.Selected
                /// </summary>
                public const uint BtnWin_1__ImageMuteTgl_SelectedState = 4;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: VidWall_Control_Widget.Button_1.Selected
                /// Button_1.Selected
                /// </summary>
                public const uint Button_1_SelectedState = 5;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: VidWall_Control_Widget.Button.Selected
                /// Button.Selected
                /// </summary>
                public const uint Button_SelectedState = 6;

            }
        }

        #endregion

        #region Construction and Initialization

        /// <summary>
        /// Initializes a new instance of the <see cref="VidWall_Control_Widget"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        internal VidWall_Control_Widget(ComponentMediator componentMediator, uint controlJoinId, uint? itemCount)
        {
            ComponentMediator = componentMediator;
            Initialize(controlJoinId, itemCount);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="VidWall_Control_Widget"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        internal VidWall_Control_Widget(ComponentMediator componentMediator, uint controlJoinId) : this(componentMediator, controlJoinId, null)
        {
        }

        /// <summary>
        /// Initializes a new instance with default itemCount.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        private void Initialize(uint controlJoinId)
        {
            Initialize(controlJoinId, null);
        }

        private Dictionary<string, Indexes> _indexLookup = new Dictionary<string, Indexes>();

        /// <summary>
        /// Initializes a new instance of the <see cref="VidWall_Control_Widget"/> component class.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        private void Initialize(uint controlJoinId, uint? itemCount)
        {
            ControlJoinId = controlJoinId; 
 
            _devices = new List<BasicTriListWithSmartObject>(); 
 

            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.BtnWin_1__FreezeTgl_PressEvent, onBtnWin_1__FreezeTgl_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.BtnWin_1__ImageMuteTgl_PressEvent, onBtnWin_1__ImageMuteTgl_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.Button_1_PressEvent, onButton_1_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.Button_PressEvent, onButton_Press);
        }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            Devices.Add(device);
            ComponentMediator.HookSmartObjectEvents(device.SmartObjects[ControlJoinId]);
        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            Devices.Remove(device);
            ComponentMediator.UnHookSmartObjectEvents(device.SmartObjects[ControlJoinId]);
        }

        #endregion

        #region CH5 Contract

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> BtnWin_1__FreezeTgl_PressEvent;
        private void onBtnWin_1__FreezeTgl_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = BtnWin_1__FreezeTgl_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> BtnWin_1__ImageMuteTgl_PressEvent;
        private void onBtnWin_1__ImageMuteTgl_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = BtnWin_1__ImageMuteTgl_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> Button_1_PressEvent;
        private void onButton_1_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = Button_1_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> Button_PressEvent;
        private void onButton_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = Button_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public void BtnWin_1__FreezeTgl_Selected(VidWall_Control_WidgetBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.BtnWin_1__FreezeTgl_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void BtnWin_1__FreezeTgl_Selected(bool digital)
        {
            BtnWin_1__FreezeTgl_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void BtnWin_1__ImageMuteTgl_Selected(VidWall_Control_WidgetBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.BtnWin_1__ImageMuteTgl_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void BtnWin_1__ImageMuteTgl_Selected(bool digital)
        {
            BtnWin_1__ImageMuteTgl_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void Button_1_Selected(VidWall_Control_WidgetBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Button_1_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void Button_1_Selected(bool digital)
        {
            Button_1_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void Button_Selected(VidWall_Control_WidgetBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Button_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void Button_Selected(bool digital)
        {
            Button_Selected((sig, component) => sig.BoolValue = digital);
        }

        #endregion

        #region Overrides

        public override int GetHashCode()
        {
            return (int)ControlJoinId;
        }

        public override string ToString()
        {
            return string.Format("Contract: {0} Component: {1} HashCode: {2} {3}", "VidWall_Control_Widget", GetType().Name, GetHashCode(), UserObject != null ? "UserObject: " + UserObject : null);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

            BtnWin_1__FreezeTgl_PressEvent = null;
            BtnWin_1__ImageMuteTgl_PressEvent = null;
            Button_1_PressEvent = null;
            Button_PressEvent = null;
        }

        #endregion
    }
}
