//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     Version: 1.3300.16.0
//
//     Project:     Standard_Classroom
//     Version:     1.0.0.0
//     Sdk:         CH5:2.8.0
//     Strategy:    Classic
//     IndexOnly:   False
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Crestron.SimplSharpPro.DeviceSupport;
using Crestron.SimplSharpPro;
using Standard_Classroom;

namespace Standard_Classroom.Main_Page
{

    /// <summary>
    /// Volume_Control_03_Panel_Widget
    /// </summary>
    public partial interface IVolume_Control_03_Panel_Widget 
    {
        object UserObject { get; set; }

        /// <summary>
        /// Main_Page.Volume_Control_03_Panel_Widget.Btn.PodMicVolDec.Press
        /// </summary>
        event EventHandler<UIEventArgs> BtnPodMicVolDec_PressEvent;

        /// <summary>
        /// Main_Page.Volume_Control_03_Panel_Widget.Btn.PodMicVolInc.Press
        /// </summary>
        event EventHandler<UIEventArgs> BtnPodMicVolInc_PressEvent;

        /// <summary>
        /// Main_Page.Volume_Control_03_Panel_Widget.Btn.PodMicVolMuteTgl.Press
        /// </summary>
        event EventHandler<UIEventArgs> BtnPodMicVolMuteTgl_PressEvent;

        /// <summary>
        /// Main_Page.Volume_Control_03_Panel_Widget.Guage.PodMicVol.Lower Touch
        /// </summary>
        event EventHandler<UIEventArgs> GuagePodMicVol_LowerTouchEvent;

        /// <summary>
        /// Main_Page.Volume_Control_03_Panel_Widget.Btn.SrcVolDec.Press
        /// </summary>
        event EventHandler<UIEventArgs> BtnSrcVolDec_PressEvent;

        /// <summary>
        /// Main_Page.Volume_Control_03_Panel_Widget.Guage.SrcVol.Lower Touch
        /// </summary>
        event EventHandler<UIEventArgs> GuageSrcVol_LowerTouchEvent;

        /// <summary>
        /// Main_Page.Volume_Control_03_Panel_Widget.Btn.SrcVolInc.Press
        /// </summary>
        event EventHandler<UIEventArgs> BtnSrcVolInc_PressEvent;

        /// <summary>
        /// Main_Page.Volume_Control_03_Panel_Widget.Guage.WirelessMicVol.Lower Touch
        /// </summary>
        event EventHandler<UIEventArgs> GuageWirelessMicVol_LowerTouchEvent;

        /// <summary>
        /// Main_Page.Volume_Control_03_Panel_Widget.Btn.SrcVolMuteTgl.Press
        /// </summary>
        event EventHandler<UIEventArgs> BtnSrcVolMuteTgl_PressEvent;

        /// <summary>
        /// Main_Page.Volume_Control_03_Panel_Widget.Btn.WirelessMicVolDec.Press
        /// </summary>
        event EventHandler<UIEventArgs> BtnWirelessMicVolDec_PressEvent;

        /// <summary>
        /// Main_Page.Volume_Control_03_Panel_Widget.Btn.WirelessMicVolInc.Press
        /// </summary>
        event EventHandler<UIEventArgs> BtnWirelessMicVolInc_PressEvent;

        /// <summary>
        /// Main_Page.Volume_Control_03_Panel_Widget.Btn.WirelessMicVolMuteTgl.Press
        /// </summary>
        event EventHandler<UIEventArgs> BtnWirelessMicVolMuteTgl_PressEvent;

        /// <summary>
        /// Volume_Control_03_Panel_Widget.Visibility Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Volume_Control_03_Panel_Widget_Visibility(Volume_Control_03_Panel_WidgetBoolInputSigDelegate callback);

        /// <summary>
        /// Volume_Control_03_Panel_Widget.Visibility Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Volume_Control_03_Panel_Widget_Visibility(bool digital);

        /// <summary>
        /// Main_Page.Volume_Control_03_Panel_Widget.Btn.PodMicVolMuteTgl.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void BtnPodMicVolMuteTgl_Selected(Volume_Control_03_Panel_WidgetBoolInputSigDelegate callback);

        /// <summary>
        /// Main_Page.Volume_Control_03_Panel_Widget.Btn.PodMicVolMuteTgl.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void BtnPodMicVolMuteTgl_Selected(bool digital);

        /// <summary>
        /// Main_Page.Volume_Control_03_Panel_Widget.Btn.SrcVolMuteTgl.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void BtnSrcVolMuteTgl_Selected(Volume_Control_03_Panel_WidgetBoolInputSigDelegate callback);

        /// <summary>
        /// Main_Page.Volume_Control_03_Panel_Widget.Btn.SrcVolMuteTgl.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void BtnSrcVolMuteTgl_Selected(bool digital);

        /// <summary>
        /// Main_Page.Volume_Control_03_Panel_Widget.Btn.WirelessMicVolMuteTgl.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void BtnWirelessMicVolMuteTgl_Selected(Volume_Control_03_Panel_WidgetBoolInputSigDelegate callback);

        /// <summary>
        /// Main_Page.Volume_Control_03_Panel_Widget.Btn.WirelessMicVolMuteTgl.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void BtnWirelessMicVolMuteTgl_Selected(bool digital);

        /// <summary>
        /// Main_Page.Volume_Control_03_Panel_Widget.Guage.PodMicVol.Lower Touch fb Feedback
        /// </summary>
        /// <param name="callback">The ushort delegate to update the panel.</param>
        void GuagePodMicVol_LowerTouchfb(Volume_Control_03_Panel_WidgetUShortInputSigDelegate callback);

        /// <summary>
        /// Main_Page.Volume_Control_03_Panel_Widget.Guage.PodMicVol.Lower Touch fb Feedback
        /// </summary>
        /// <param name="callback">The ushort analog to update the panel.</param>
        void GuagePodMicVol_LowerTouchfb(ushort analog);

        /// <summary>
        /// Main_Page.Volume_Control_03_Panel_Widget.Guage.PodMicVol.Lower Touch fb Feedback
        /// </summary>
        /// <param name="callback">The short analog to update the panel.</param>
        void GuagePodMicVol_LowerTouchfb(short analog);

        /// <summary>
        /// Main_Page.Volume_Control_03_Panel_Widget.Guage.SrcVol.Lower Touch fb Feedback
        /// </summary>
        /// <param name="callback">The ushort delegate to update the panel.</param>
        void GuageSrcVol_LowerTouchfb(Volume_Control_03_Panel_WidgetUShortInputSigDelegate callback);

        /// <summary>
        /// Main_Page.Volume_Control_03_Panel_Widget.Guage.SrcVol.Lower Touch fb Feedback
        /// </summary>
        /// <param name="callback">The ushort analog to update the panel.</param>
        void GuageSrcVol_LowerTouchfb(ushort analog);

        /// <summary>
        /// Main_Page.Volume_Control_03_Panel_Widget.Guage.SrcVol.Lower Touch fb Feedback
        /// </summary>
        /// <param name="callback">The short analog to update the panel.</param>
        void GuageSrcVol_LowerTouchfb(short analog);

        /// <summary>
        /// Main_Page.Volume_Control_03_Panel_Widget.Guage.WirelessMicVol.Lower Touch fb Feedback
        /// </summary>
        /// <param name="callback">The ushort delegate to update the panel.</param>
        void GuageWirelessMicVol_LowerTouchfb(Volume_Control_03_Panel_WidgetUShortInputSigDelegate callback);

        /// <summary>
        /// Main_Page.Volume_Control_03_Panel_Widget.Guage.WirelessMicVol.Lower Touch fb Feedback
        /// </summary>
        /// <param name="callback">The ushort analog to update the panel.</param>
        void GuageWirelessMicVol_LowerTouchfb(ushort analog);

        /// <summary>
        /// Main_Page.Volume_Control_03_Panel_Widget.Guage.WirelessMicVol.Lower Touch fb Feedback
        /// </summary>
        /// <param name="callback">The short analog to update the panel.</param>
        void GuageWirelessMicVol_LowerTouchfb(short analog);
    }

    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="boolInputSig">The <see cref="BoolInputSig"/> signal data.</param>
    /// <param name="volume_control_03_panel_widget">The <see cref="IVolume_Control_03_Panel_Widget"/> on which to apply the feedback.</param>
    public delegate void Volume_Control_03_Panel_WidgetBoolInputSigDelegate(BoolInputSig boolInputSig, IVolume_Control_03_Panel_Widget volume_control_03_panel_widget);
    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="uShortInputSig">The <see cref="UShortInputSig"/> signal data.</param>
    /// <param name="volume_control_03_panel_widget">The <see cref="IVolume_Control_03_Panel_Widget"/> on which to apply the feedback.</param>
    public delegate void Volume_Control_03_Panel_WidgetUShortInputSigDelegate(UShortInputSig uShortInputSig, IVolume_Control_03_Panel_Widget volume_control_03_panel_widget);

    /// <summary>
    /// Volume_Control_03_Panel_Widget
    /// </summary>
    internal partial class Volume_Control_03_Panel_Widget : IVolume_Control_03_Panel_Widget, IDisposable
    {
        #region Standard CH5 Component members

        private ComponentMediator ComponentMediator { get; set; }

        public object UserObject { get; set; }

        /// <summary>
        /// Gets the ControlJoinId a.k.a. SmartObjectId.  This Id identifies the extender symbol.
        /// </summary>
        public uint ControlJoinId { get; private set; }

        private IList<BasicTriListWithSmartObject> _devices;

        /// <summary>
        /// Gets the list of devices.
        /// </summary>
        public IList<BasicTriListWithSmartObject> Devices { get { return _devices; } }

        #endregion

        #region Joins

        private static class Joins
        {
            /// <summary>
            /// Digital signals,
            /// </summary>
            internal static class Booleans
            {
                /// <summary>
                /// Output or Event digital signal from panel to Control System: Main_Page.Volume_Control_03_Panel_Widget.BtnPodMicVolDec.Press
                /// Main_Page.Volume_Control_03_Panel_Widget.Btn.PodMicVolDec.Press
                /// </summary>
                public const uint BtnPodMicVolDec_PressEvent = 2;

                /// <summary>
                /// Output or Event digital signal from panel to Control System: Main_Page.Volume_Control_03_Panel_Widget.BtnPodMicVolInc.Press
                /// Main_Page.Volume_Control_03_Panel_Widget.Btn.PodMicVolInc.Press
                /// </summary>
                public const uint BtnPodMicVolInc_PressEvent = 3;

                /// <summary>
                /// Output or Event digital signal from panel to Control System: Main_Page.Volume_Control_03_Panel_Widget.BtnPodMicVolMuteTgl.Press
                /// Main_Page.Volume_Control_03_Panel_Widget.Btn.PodMicVolMuteTgl.Press
                /// </summary>
                public const uint BtnPodMicVolMuteTgl_PressEvent = 4;

                /// <summary>
                /// Output or Event digital signal from panel to Control System: Main_Page.Volume_Control_03_Panel_Widget.BtnSrcVolDec.Press
                /// Main_Page.Volume_Control_03_Panel_Widget.Btn.SrcVolDec.Press
                /// </summary>
                public const uint BtnSrcVolDec_PressEvent = 5;

                /// <summary>
                /// Output or Event digital signal from panel to Control System: Main_Page.Volume_Control_03_Panel_Widget.BtnSrcVolInc.Press
                /// Main_Page.Volume_Control_03_Panel_Widget.Btn.SrcVolInc.Press
                /// </summary>
                public const uint BtnSrcVolInc_PressEvent = 6;

                /// <summary>
                /// Output or Event digital signal from panel to Control System: Main_Page.Volume_Control_03_Panel_Widget.BtnSrcVolMuteTgl.Press
                /// Main_Page.Volume_Control_03_Panel_Widget.Btn.SrcVolMuteTgl.Press
                /// </summary>
                public const uint BtnSrcVolMuteTgl_PressEvent = 7;

                /// <summary>
                /// Output or Event digital signal from panel to Control System: Main_Page.Volume_Control_03_Panel_Widget.BtnWirelessMicVolDec.Press
                /// Main_Page.Volume_Control_03_Panel_Widget.Btn.WirelessMicVolDec.Press
                /// </summary>
                public const uint BtnWirelessMicVolDec_PressEvent = 8;

                /// <summary>
                /// Output or Event digital signal from panel to Control System: Main_Page.Volume_Control_03_Panel_Widget.BtnWirelessMicVolInc.Press
                /// Main_Page.Volume_Control_03_Panel_Widget.Btn.WirelessMicVolInc.Press
                /// </summary>
                public const uint BtnWirelessMicVolInc_PressEvent = 9;

                /// <summary>
                /// Output or Event digital signal from panel to Control System: Main_Page.Volume_Control_03_Panel_Widget.BtnWirelessMicVolMuteTgl.Press
                /// Main_Page.Volume_Control_03_Panel_Widget.Btn.WirelessMicVolMuteTgl.Press
                /// </summary>
                public const uint BtnWirelessMicVolMuteTgl_PressEvent = 10;


                /// <summary>
                /// Input or Feedback digital signal from Control System to panel: Main_Page.Volume_Control_03_Panel_Widget.Visibility
                /// Volume_Control_03_Panel_Widget.Visibility
                /// </summary>
                public const uint Volume_Control_03_Panel_Widget_VisibilityState = 1;

                /// <summary>
                /// Input or Feedback digital signal from Control System to panel: Main_Page.Volume_Control_03_Panel_Widget.BtnPodMicVolMuteTgl.Selected
                /// Main_Page.Volume_Control_03_Panel_Widget.Btn.PodMicVolMuteTgl.Selected
                /// </summary>
                public const uint BtnPodMicVolMuteTgl_SelectedState = 3;

                /// <summary>
                /// Input or Feedback digital signal from Control System to panel: Main_Page.Volume_Control_03_Panel_Widget.BtnSrcVolMuteTgl.Selected
                /// Main_Page.Volume_Control_03_Panel_Widget.Btn.SrcVolMuteTgl.Selected
                /// </summary>
                public const uint BtnSrcVolMuteTgl_SelectedState = 4;

                /// <summary>
                /// Input or Feedback digital signal from Control System to panel: Main_Page.Volume_Control_03_Panel_Widget.BtnWirelessMicVolMuteTgl.Selected
                /// Main_Page.Volume_Control_03_Panel_Widget.Btn.WirelessMicVolMuteTgl.Selected
                /// </summary>
                public const uint BtnWirelessMicVolMuteTgl_SelectedState = 5;

            }
            /// <summary>
            /// Analog signals.
            /// </summary>
            internal static class Numerics
            {
                /// <summary>
                /// Output or Event analog signal from panel to Control System: Main_Page.Volume_Control_03_Panel_Widget.GuagePodMicVol.LowerTouch
                /// Main_Page.Volume_Control_03_Panel_Widget.Guage.PodMicVol.Lower Touch
                /// </summary>
                public const uint GuagePodMicVol_LowerTouchEvent = 4;

                /// <summary>
                /// Output or Event analog signal from panel to Control System: Main_Page.Volume_Control_03_Panel_Widget.GuageSrcVol.LowerTouch
                /// Main_Page.Volume_Control_03_Panel_Widget.Guage.SrcVol.Lower Touch
                /// </summary>
                public const uint GuageSrcVol_LowerTouchEvent = 5;

                /// <summary>
                /// Output or Event analog signal from panel to Control System: Main_Page.Volume_Control_03_Panel_Widget.GuageWirelessMicVol.LowerTouch
                /// Main_Page.Volume_Control_03_Panel_Widget.Guage.WirelessMicVol.Lower Touch
                /// </summary>
                public const uint GuageWirelessMicVol_LowerTouchEvent = 6;


                /// <summary>
                /// Input or Feedback analog signal from Control System to panel: Main_Page.Volume_Control_03_Panel_Widget.GuagePodMicVol.LowerTouchfb
                /// Main_Page.Volume_Control_03_Panel_Widget.Guage.PodMicVol.Lower Touch fb
                /// </summary>
                public const uint GuagePodMicVol_LowerTouchfbState = 4;

                /// <summary>
                /// Input or Feedback analog signal from Control System to panel: Main_Page.Volume_Control_03_Panel_Widget.GuageSrcVol.LowerTouchfb
                /// Main_Page.Volume_Control_03_Panel_Widget.Guage.SrcVol.Lower Touch fb
                /// </summary>
                public const uint GuageSrcVol_LowerTouchfbState = 5;

                /// <summary>
                /// Input or Feedback analog signal from Control System to panel: Main_Page.Volume_Control_03_Panel_Widget.GuageWirelessMicVol.LowerTouchfb
                /// Main_Page.Volume_Control_03_Panel_Widget.Guage.WirelessMicVol.Lower Touch fb
                /// </summary>
                public const uint GuageWirelessMicVol_LowerTouchfbState = 6;

            }
        }

        #endregion

        #region Construction and Initialization

        /// <summary>
        /// Initializes a new instance of the <see cref="Volume_Control_03_Panel_Widget"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        internal Volume_Control_03_Panel_Widget(ComponentMediator componentMediator, uint controlJoinId, uint? itemCount)
        {
            ComponentMediator = componentMediator;
            Initialize(controlJoinId, itemCount);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Volume_Control_03_Panel_Widget"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        internal Volume_Control_03_Panel_Widget(ComponentMediator componentMediator, uint controlJoinId) : this(componentMediator, controlJoinId, null)
        {
        }

        /// <summary>
        /// Initializes a new instance with default itemCount.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        private void Initialize(uint controlJoinId)
        {
            Initialize(controlJoinId, null);
        }

        private Dictionary<string, Indexes> _indexLookup = new Dictionary<string, Indexes>();

        /// <summary>
        /// Initializes a new instance of the <see cref="Volume_Control_03_Panel_Widget"/> component class.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        private void Initialize(uint controlJoinId, uint? itemCount)
        {
            ControlJoinId = controlJoinId; 
 
            _devices = new List<BasicTriListWithSmartObject>(); 
 

            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.BtnPodMicVolDec_PressEvent, onBtnPodMicVolDec_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.BtnPodMicVolInc_PressEvent, onBtnPodMicVolInc_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.BtnPodMicVolMuteTgl_PressEvent, onBtnPodMicVolMuteTgl_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.BtnSrcVolDec_PressEvent, onBtnSrcVolDec_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.BtnSrcVolInc_PressEvent, onBtnSrcVolInc_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.BtnSrcVolMuteTgl_PressEvent, onBtnSrcVolMuteTgl_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.BtnWirelessMicVolDec_PressEvent, onBtnWirelessMicVolDec_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.BtnWirelessMicVolInc_PressEvent, onBtnWirelessMicVolInc_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.BtnWirelessMicVolMuteTgl_PressEvent, onBtnWirelessMicVolMuteTgl_Press);
            ComponentMediator.ConfigureNumericEvent(controlJoinId, Joins.Numerics.GuagePodMicVol_LowerTouchEvent, onGuagePodMicVol_LowerTouch);
            ComponentMediator.ConfigureNumericEvent(controlJoinId, Joins.Numerics.GuageSrcVol_LowerTouchEvent, onGuageSrcVol_LowerTouch);
            ComponentMediator.ConfigureNumericEvent(controlJoinId, Joins.Numerics.GuageWirelessMicVol_LowerTouchEvent, onGuageWirelessMicVol_LowerTouch);
        }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            Devices.Add(device);
            ComponentMediator.HookSmartObjectEvents(device.SmartObjects[ControlJoinId]);
        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            Devices.Remove(device);
            ComponentMediator.UnHookSmartObjectEvents(device.SmartObjects[ControlJoinId]);
        }

        #endregion

        #region CH5 Contract

        /// <summary>
        /// Event Main_Page.Volume_Control_03_Panel_Widget.Btn.PodMicVolDec.Press (from panel to Control System)
        /// </summary>
        public event EventHandler<UIEventArgs> BtnPodMicVolDec_PressEvent;
        private void onBtnPodMicVolDec_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = BtnPodMicVolDec_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <summary>
        /// Event Main_Page.Volume_Control_03_Panel_Widget.Btn.PodMicVolInc.Press (from panel to Control System)
        /// </summary>
        public event EventHandler<UIEventArgs> BtnPodMicVolInc_PressEvent;
        private void onBtnPodMicVolInc_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = BtnPodMicVolInc_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <summary>
        /// Event Main_Page.Volume_Control_03_Panel_Widget.Btn.PodMicVolMuteTgl.Press (from panel to Control System)
        /// </summary>
        public event EventHandler<UIEventArgs> BtnPodMicVolMuteTgl_PressEvent;
        private void onBtnPodMicVolMuteTgl_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = BtnPodMicVolMuteTgl_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <summary>
        /// Event Main_Page.Volume_Control_03_Panel_Widget.Guage.PodMicVol.Lower Touch (from panel to Control System)
        /// </summary>
        public event EventHandler<UIEventArgs> GuagePodMicVol_LowerTouchEvent;
        private void onGuagePodMicVol_LowerTouch(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = GuagePodMicVol_LowerTouchEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <summary>
        /// Event Main_Page.Volume_Control_03_Panel_Widget.Btn.SrcVolDec.Press (from panel to Control System)
        /// </summary>
        public event EventHandler<UIEventArgs> BtnSrcVolDec_PressEvent;
        private void onBtnSrcVolDec_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = BtnSrcVolDec_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <summary>
        /// Event Main_Page.Volume_Control_03_Panel_Widget.Guage.SrcVol.Lower Touch (from panel to Control System)
        /// </summary>
        public event EventHandler<UIEventArgs> GuageSrcVol_LowerTouchEvent;
        private void onGuageSrcVol_LowerTouch(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = GuageSrcVol_LowerTouchEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <summary>
        /// Event Main_Page.Volume_Control_03_Panel_Widget.Btn.SrcVolInc.Press (from panel to Control System)
        /// </summary>
        public event EventHandler<UIEventArgs> BtnSrcVolInc_PressEvent;
        private void onBtnSrcVolInc_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = BtnSrcVolInc_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <summary>
        /// Event Main_Page.Volume_Control_03_Panel_Widget.Guage.WirelessMicVol.Lower Touch (from panel to Control System)
        /// </summary>
        public event EventHandler<UIEventArgs> GuageWirelessMicVol_LowerTouchEvent;
        private void onGuageWirelessMicVol_LowerTouch(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = GuageWirelessMicVol_LowerTouchEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <summary>
        /// Event Main_Page.Volume_Control_03_Panel_Widget.Btn.SrcVolMuteTgl.Press (from panel to Control System)
        /// </summary>
        public event EventHandler<UIEventArgs> BtnSrcVolMuteTgl_PressEvent;
        private void onBtnSrcVolMuteTgl_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = BtnSrcVolMuteTgl_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <summary>
        /// Event Main_Page.Volume_Control_03_Panel_Widget.Btn.WirelessMicVolDec.Press (from panel to Control System)
        /// </summary>
        public event EventHandler<UIEventArgs> BtnWirelessMicVolDec_PressEvent;
        private void onBtnWirelessMicVolDec_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = BtnWirelessMicVolDec_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <summary>
        /// Event Main_Page.Volume_Control_03_Panel_Widget.Btn.WirelessMicVolInc.Press (from panel to Control System)
        /// </summary>
        public event EventHandler<UIEventArgs> BtnWirelessMicVolInc_PressEvent;
        private void onBtnWirelessMicVolInc_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = BtnWirelessMicVolInc_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <summary>
        /// Event Main_Page.Volume_Control_03_Panel_Widget.Btn.WirelessMicVolMuteTgl.Press (from panel to Control System)
        /// </summary>
        public event EventHandler<UIEventArgs> BtnWirelessMicVolMuteTgl_PressEvent;
        private void onBtnWirelessMicVolMuteTgl_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = BtnWirelessMicVolMuteTgl_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <summary>
        /// Boolean feedback Main_Page.Volume_Control_03_Panel_Widget.Btn.PodMicVolMuteTgl.Selected (from Control System to Panel)
        /// </summary>
        public void BtnPodMicVolMuteTgl_Selected(Volume_Control_03_Panel_WidgetBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.BtnPodMicVolMuteTgl_SelectedState], this);
            }
        }

        /// <summary>
        /// Boolean feedback Main_Page.Volume_Control_03_Panel_Widget.Btn.PodMicVolMuteTgl.Selected (from Control System to Panel)
        /// </summary>
        public void BtnPodMicVolMuteTgl_Selected(bool digital)
        {
            BtnPodMicVolMuteTgl_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <summary>
        /// Boolean feedback Main_Page.Volume_Control_03_Panel_Widget.Btn.SrcVolMuteTgl.Selected (from Control System to Panel)
        /// </summary>
        public void BtnSrcVolMuteTgl_Selected(Volume_Control_03_Panel_WidgetBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.BtnSrcVolMuteTgl_SelectedState], this);
            }
        }

        /// <summary>
        /// Boolean feedback Main_Page.Volume_Control_03_Panel_Widget.Btn.SrcVolMuteTgl.Selected (from Control System to Panel)
        /// </summary>
        public void BtnSrcVolMuteTgl_Selected(bool digital)
        {
            BtnSrcVolMuteTgl_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <summary>
        /// Boolean feedback Main_Page.Volume_Control_03_Panel_Widget.Btn.WirelessMicVolMuteTgl.Selected (from Control System to Panel)
        /// </summary>
        public void BtnWirelessMicVolMuteTgl_Selected(Volume_Control_03_Panel_WidgetBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.BtnWirelessMicVolMuteTgl_SelectedState], this);
            }
        }

        /// <summary>
        /// Boolean feedback Main_Page.Volume_Control_03_Panel_Widget.Btn.WirelessMicVolMuteTgl.Selected (from Control System to Panel)
        /// </summary>
        public void BtnWirelessMicVolMuteTgl_Selected(bool digital)
        {
            BtnWirelessMicVolMuteTgl_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <summary>
        /// Boolean feedback Volume_Control_03_Panel_Widget.Visibility (from Control System to Panel)
        /// </summary>
        public void Volume_Control_03_Panel_Widget_Visibility(Volume_Control_03_Panel_WidgetBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Volume_Control_03_Panel_Widget_VisibilityState], this);
            }
        }

        /// <summary>
        /// Boolean feedback Volume_Control_03_Panel_Widget.Visibility (from Control System to Panel)
        /// </summary>
        public void Volume_Control_03_Panel_Widget_Visibility(bool digital)
        {
            Volume_Control_03_Panel_Widget_Visibility((sig, component) => sig.BoolValue = digital);
        }

        /// <summary>
        /// Numeric feedback Main_Page.Volume_Control_03_Panel_Widget.Guage.PodMicVol.Lower Touch fb
        /// </summary>
        /// <param name="itemIndex">Index of the Widget List (0 based).</param>
        /// <param name="callback">The ushort delegate to update the panel.</param>
        public void GuagePodMicVol_LowerTouchfb(Volume_Control_03_Panel_WidgetUShortInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].UShortInput[Joins.Numerics.GuagePodMicVol_LowerTouchfbState], this);
            }
        }

        /// <summary>
        /// Numeric feedback Main_Page.Volume_Control_03_Panel_Widget.Guage.PodMicVol.Lower Touch fb
        /// </summary>
        /// <param name="analog">The ushort analog to update the panel.</param>
        public void GuagePodMicVol_LowerTouchfb(ushort analog)
        {
            GuagePodMicVol_LowerTouchfb((sig, component) => sig.UShortValue = analog);
        }

        /// <summary>
        /// Numeric feedback Main_Page.Volume_Control_03_Panel_Widget.Guage.PodMicVol.Lower Touch fb
        /// </summary>
        /// <param name="analog">The short analog to update the panel.</param>
        public void GuagePodMicVol_LowerTouchfb(short analog)
        {
            GuagePodMicVol_LowerTouchfb((sig, component) => sig.ShortValue = analog);
        }
        /// <summary>
        /// Numeric feedback Main_Page.Volume_Control_03_Panel_Widget.Guage.SrcVol.Lower Touch fb
        /// </summary>
        /// <param name="itemIndex">Index of the Widget List (0 based).</param>
        /// <param name="callback">The ushort delegate to update the panel.</param>
        public void GuageSrcVol_LowerTouchfb(Volume_Control_03_Panel_WidgetUShortInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].UShortInput[Joins.Numerics.GuageSrcVol_LowerTouchfbState], this);
            }
        }

        /// <summary>
        /// Numeric feedback Main_Page.Volume_Control_03_Panel_Widget.Guage.SrcVol.Lower Touch fb
        /// </summary>
        /// <param name="analog">The ushort analog to update the panel.</param>
        public void GuageSrcVol_LowerTouchfb(ushort analog)
        {
            GuageSrcVol_LowerTouchfb((sig, component) => sig.UShortValue = analog);
        }

        /// <summary>
        /// Numeric feedback Main_Page.Volume_Control_03_Panel_Widget.Guage.SrcVol.Lower Touch fb
        /// </summary>
        /// <param name="analog">The short analog to update the panel.</param>
        public void GuageSrcVol_LowerTouchfb(short analog)
        {
            GuageSrcVol_LowerTouchfb((sig, component) => sig.ShortValue = analog);
        }
        /// <summary>
        /// Numeric feedback Main_Page.Volume_Control_03_Panel_Widget.Guage.WirelessMicVol.Lower Touch fb
        /// </summary>
        /// <param name="itemIndex">Index of the Widget List (0 based).</param>
        /// <param name="callback">The ushort delegate to update the panel.</param>
        public void GuageWirelessMicVol_LowerTouchfb(Volume_Control_03_Panel_WidgetUShortInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].UShortInput[Joins.Numerics.GuageWirelessMicVol_LowerTouchfbState], this);
            }
        }

        /// <summary>
        /// Numeric feedback Main_Page.Volume_Control_03_Panel_Widget.Guage.WirelessMicVol.Lower Touch fb
        /// </summary>
        /// <param name="analog">The ushort analog to update the panel.</param>
        public void GuageWirelessMicVol_LowerTouchfb(ushort analog)
        {
            GuageWirelessMicVol_LowerTouchfb((sig, component) => sig.UShortValue = analog);
        }

        /// <summary>
        /// Numeric feedback Main_Page.Volume_Control_03_Panel_Widget.Guage.WirelessMicVol.Lower Touch fb
        /// </summary>
        /// <param name="analog">The short analog to update the panel.</param>
        public void GuageWirelessMicVol_LowerTouchfb(short analog)
        {
            GuageWirelessMicVol_LowerTouchfb((sig, component) => sig.ShortValue = analog);
        }

        #endregion

        #region Overrides

        public override int GetHashCode()
        {
            return (int)ControlJoinId;
        }

        public override string ToString()
        {
            return string.Format("Contract: {0} Component: {1} HashCode: {2} {3}", "Volume_Control_03_Panel_Widget", GetType().Name, GetHashCode(), UserObject != null ? "UserObject: " + UserObject : null);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

            BtnPodMicVolDec_PressEvent = null;
            BtnPodMicVolInc_PressEvent = null;
            BtnPodMicVolMuteTgl_PressEvent = null;
            GuagePodMicVol_LowerTouchEvent = null;
            BtnSrcVolDec_PressEvent = null;
            GuageSrcVol_LowerTouchEvent = null;
            BtnSrcVolInc_PressEvent = null;
            GuageWirelessMicVol_LowerTouchEvent = null;
            BtnSrcVolMuteTgl_PressEvent = null;
            BtnWirelessMicVolDec_PressEvent = null;
            BtnWirelessMicVolInc_PressEvent = null;
            BtnWirelessMicVolMuteTgl_PressEvent = null;
        }

        #endregion
    }
}
