//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     AppHost:     2.1.48.0
//     UI Plugin:   1.3601.24.0
//
//     Project:     Active_Learning_Classroom
//     Version:     1.0.0.0
//     Sdk:         CH5:2.10.0
//     Strategy:    Classic
//     IndexOnly:   False
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using Active_Learning_Classroom;

namespace Active_Learning_Classroom.Main_Page.Pods_List
{

    /// <summary>
    /// Allow events by list item and states (feedbacks) to be set by item index.
    /// </summary>
    public partial interface IBtnListPodSelectByItem
    {
        /// <summary>
        /// Fires on button list presses.  Event carries <see="IndexedButtonEventArgs"/> with ButtonIndex property (0 based).
        /// </summary>
        event EventHandler<IndexedButtonEventArgs> Button_PressEvent;

        /// <summary>
        /// Main_Page.Pods_List.Button1.ItemSelected Feedback
        /// </summary>
        /// <param name="buttonIndex">The index of the button (0 based).</param>
        /// <param name="callback">The delegate to set the feedback.</param>
        void Button_Selected(ushort buttonIndex, BtnListPodSelectBoolInputSigDelegate callback);

        /// <summary>
        /// Helper Main_Page.Pods_List.Button1.ItemSelected Feedback
        /// </summary>
        /// <param name="buttonIndex">The index of the button (0 based).</param>
        /// <param name="digital">The <see="bool"/> value to set on the panel.</param>
        void Button_Selected(ushort buttonIndex, bool digital);

        /// <summary>
        /// Main_Page.Pods_List.Button1.Visible Feedback
        /// </summary>
        /// <param name="buttonIndex">The index of the button (0 based).</param>
        /// <param name="callback">The delegate to set the feedback.</param>
        void Button_Visible(ushort buttonIndex, BtnListPodSelectBoolInputSigDelegate callback);

        /// <summary>
        /// Helper Main_Page.Pods_List.Button1.Visible Feedback
        /// </summary>
        /// <param name="buttonIndex">The index of the button (0 based).</param>
        /// <param name="digital">The <see="bool"/> value to set on the panel.</param>
        void Button_Visible(ushort buttonIndex, bool digital);
    }


    /// <summary>
    /// Search List
    /// </summary>
    internal partial class BtnListPodSelect
    {
        #region CH5 Contract
        /// <inheritdoc/>
        public event EventHandler<IndexedButtonEventArgs> Button_PressEvent;
        private void onButton_Press(IndexedEventArgs eventArgs)
        {
            EventHandler<IndexedButtonEventArgs> handler = Button_PressEvent;
            if (handler != null)
                handler(this, new IndexedButtonEventArgs((SmartObjectEventArgs)eventArgs.SigArgs, eventArgs.JoinIndex));
        }
                
        /// <inheritdoc/>
        public void Button_Selected(ushort buttonIndex, BtnListPodSelectBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Button_1_Button_SelectedState + (uint) buttonIndex], this);
            }
        }

        /// <inheritdoc/>
        public void Button_Selected(ushort buttonIndex, bool digital)
        {
            Button_Selected(buttonIndex, (sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void Button_Visible(ushort buttonIndex, BtnListPodSelectBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Button_1_Button_VisibleState + (uint) buttonIndex], this);
            }
        }

        /// <inheritdoc/>
        public void Button_Visible(ushort buttonIndex, bool digital)
        {
            Button_Visible(buttonIndex, (sig, component) => sig.BoolValue = digital);
        }

        #endregion
    }

    /// <summary>
    /// BtnList.PodSelect
    /// </summary>
    public partial interface IBtnListPodSelect : IBtnListPodSelectByItem
    {
        object UserObject { get; set; }

        /// <summary>
        /// Event Main_Page.Pods_List.Button1.ItemPress (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> Button_1_Button_PressEvent;

        /// <summary>
        /// Event Main_Page.Pods_List.Button2.ItemPress (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> Button_2_Button_PressEvent;

        /// <summary>
        /// Event Main_Page.Pods_List.Button3.ItemPress (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> Button_3_Button_PressEvent;

        /// <summary>
        /// Event Main_Page.Pods_List.Button4.ItemPress (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> Button_4_Button_PressEvent;

        /// <summary>
        /// Event Main_Page.Pods_List.Button5.ItemPress (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> Button_5_Button_PressEvent;

        /// <summary>
        /// Event Main_Page.Pods_List.Button6.ItemPress (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> Button_6_Button_PressEvent;

        /// <summary>
        /// Event Main_Page.Pods_List.Button7.ItemPress (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> Button_7_Button_PressEvent;

        /// <summary>
        /// Event Main_Page.Pods_List.Button8.ItemPress (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> Button_8_Button_PressEvent;

        /// <summary>
        /// Event Main_Page.Pods_List.Button9.ItemPress (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> Button_9_Button_PressEvent;

        /// <summary>
        /// Event Main_Page.Pods_List.Button10.ItemPress (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> Button_10_Button_PressEvent;

        /// <summary>
        /// Main_Page.Pods_List.Button1.ItemSelected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Button_1_Button_Selected(BtnListPodSelectBoolInputSigDelegate callback);

        /// <summary>
        /// Main_Page.Pods_List.Button1.ItemSelected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Button_1_Button_Selected(bool digital);

        /// <summary>
        /// Main_Page.Pods_List.Button2.ItemSelected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Button_2_Button_Selected(BtnListPodSelectBoolInputSigDelegate callback);

        /// <summary>
        /// Main_Page.Pods_List.Button2.ItemSelected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Button_2_Button_Selected(bool digital);

        /// <summary>
        /// Main_Page.Pods_List.Button3.ItemSelected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Button_3_Button_Selected(BtnListPodSelectBoolInputSigDelegate callback);

        /// <summary>
        /// Main_Page.Pods_List.Button3.ItemSelected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Button_3_Button_Selected(bool digital);

        /// <summary>
        /// Main_Page.Pods_List.Button4.ItemSelected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Button_4_Button_Selected(BtnListPodSelectBoolInputSigDelegate callback);

        /// <summary>
        /// Main_Page.Pods_List.Button4.ItemSelected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Button_4_Button_Selected(bool digital);

        /// <summary>
        /// Main_Page.Pods_List.Button5.ItemSelected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Button_5_Button_Selected(BtnListPodSelectBoolInputSigDelegate callback);

        /// <summary>
        /// Main_Page.Pods_List.Button5.ItemSelected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Button_5_Button_Selected(bool digital);

        /// <summary>
        /// Main_Page.Pods_List.Button6.ItemSelected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Button_6_Button_Selected(BtnListPodSelectBoolInputSigDelegate callback);

        /// <summary>
        /// Main_Page.Pods_List.Button6.ItemSelected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Button_6_Button_Selected(bool digital);

        /// <summary>
        /// Main_Page.Pods_List.Button7.ItemSelected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Button_7_Button_Selected(BtnListPodSelectBoolInputSigDelegate callback);

        /// <summary>
        /// Main_Page.Pods_List.Button7.ItemSelected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Button_7_Button_Selected(bool digital);

        /// <summary>
        /// Main_Page.Pods_List.Button8.ItemSelected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Button_8_Button_Selected(BtnListPodSelectBoolInputSigDelegate callback);

        /// <summary>
        /// Main_Page.Pods_List.Button8.ItemSelected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Button_8_Button_Selected(bool digital);

        /// <summary>
        /// Main_Page.Pods_List.Button9.ItemSelected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Button_9_Button_Selected(BtnListPodSelectBoolInputSigDelegate callback);

        /// <summary>
        /// Main_Page.Pods_List.Button9.ItemSelected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Button_9_Button_Selected(bool digital);

        /// <summary>
        /// Main_Page.Pods_List.Button10.ItemSelected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Button_10_Button_Selected(BtnListPodSelectBoolInputSigDelegate callback);

        /// <summary>
        /// Main_Page.Pods_List.Button10.ItemSelected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Button_10_Button_Selected(bool digital);

        /// <summary>
        /// Main_Page.Pods_List.Button1.Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Button_1_Button_Visible(BtnListPodSelectBoolInputSigDelegate callback);

        /// <summary>
        /// Main_Page.Pods_List.Button1.Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Button_1_Button_Visible(bool digital);

        /// <summary>
        /// Main_Page.Pods_List.Button2.Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Button_2_Button_Visible(BtnListPodSelectBoolInputSigDelegate callback);

        /// <summary>
        /// Main_Page.Pods_List.Button2.Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Button_2_Button_Visible(bool digital);

        /// <summary>
        /// Main_Page.Pods_List.Button3.Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Button_3_Button_Visible(BtnListPodSelectBoolInputSigDelegate callback);

        /// <summary>
        /// Main_Page.Pods_List.Button3.Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Button_3_Button_Visible(bool digital);

        /// <summary>
        /// Main_Page.Pods_List.Button4.Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Button_4_Button_Visible(BtnListPodSelectBoolInputSigDelegate callback);

        /// <summary>
        /// Main_Page.Pods_List.Button4.Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Button_4_Button_Visible(bool digital);

        /// <summary>
        /// Main_Page.Pods_List.Button5.Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Button_5_Button_Visible(BtnListPodSelectBoolInputSigDelegate callback);

        /// <summary>
        /// Main_Page.Pods_List.Button5.Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Button_5_Button_Visible(bool digital);

        /// <summary>
        /// Main_Page.Pods_List.Button6.Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Button_6_Button_Visible(BtnListPodSelectBoolInputSigDelegate callback);

        /// <summary>
        /// Main_Page.Pods_List.Button6.Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Button_6_Button_Visible(bool digital);

        /// <summary>
        /// Main_Page.Pods_List.Button7.Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Button_7_Button_Visible(BtnListPodSelectBoolInputSigDelegate callback);

        /// <summary>
        /// Main_Page.Pods_List.Button7.Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Button_7_Button_Visible(bool digital);

        /// <summary>
        /// Main_Page.Pods_List.Button8.Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Button_8_Button_Visible(BtnListPodSelectBoolInputSigDelegate callback);

        /// <summary>
        /// Main_Page.Pods_List.Button8.Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Button_8_Button_Visible(bool digital);

        /// <summary>
        /// Main_Page.Pods_List.Button9.Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Button_9_Button_Visible(BtnListPodSelectBoolInputSigDelegate callback);

        /// <summary>
        /// Main_Page.Pods_List.Button9.Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Button_9_Button_Visible(bool digital);

        /// <summary>
        /// Main_Page.Pods_List.Button10.Visible Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Button_10_Button_Visible(BtnListPodSelectBoolInputSigDelegate callback);

        /// <summary>
        /// Main_Page.Pods_List.Button10.Visible Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Button_10_Button_Visible(bool digital);
    }

    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="boolInputSig">The <see cref="BoolInputSig"/> joinInfo data.</param>
    /// <param name="btnlistpodselect">The <see cref="IBtnListPodSelect"/> on which to apply the feedback.</param>
    public delegate void BtnListPodSelectBoolInputSigDelegate(BoolInputSig boolInputSig, IBtnListPodSelect btnlistpodselect);

    /// <summary>
    /// BtnList.PodSelect
    /// </summary>
    internal partial class BtnListPodSelect : IBtnListPodSelect, IDisposable
    {
        #region Standard CH5 Component members

        private ComponentMediator ComponentMediator { get; set; }

        public object UserObject { get; set; }

        /// <summary>
        /// Gets the ControlJoinId a.k.a. SmartObjectId.  This Id identifies the extender symbol.
        /// </summary>
        public uint ControlJoinId { get; private set; }

        private IList<BasicTriListWithSmartObject> _devices;

        /// <summary>
        /// Gets the list of devices.
        /// </summary>
        public IList<BasicTriListWithSmartObject> Devices { get { return _devices; } }

        #endregion

        #region Joins

        private static class Joins
        {
            /// <summary>
            /// Digital signals,
            /// </summary>
            internal static class Booleans
            {
                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: Main_Page.Pods_List.BtnListPodSelect.Button1ItemPress
                /// Main_Page.Pods_List.Button1.ItemPress
                /// </summary>
                public const uint Button_1_Button_PressEvent = 1001;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: Main_Page.Pods_List.BtnListPodSelect.Button2ItemPress
                /// Main_Page.Pods_List.Button2.ItemPress
                /// </summary>
                public const uint Button_2_Button_PressEvent = 1002;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: Main_Page.Pods_List.BtnListPodSelect.Button3ItemPress
                /// Main_Page.Pods_List.Button3.ItemPress
                /// </summary>
                public const uint Button_3_Button_PressEvent = 1003;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: Main_Page.Pods_List.BtnListPodSelect.Button4ItemPress
                /// Main_Page.Pods_List.Button4.ItemPress
                /// </summary>
                public const uint Button_4_Button_PressEvent = 1004;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: Main_Page.Pods_List.BtnListPodSelect.Button5ItemPress
                /// Main_Page.Pods_List.Button5.ItemPress
                /// </summary>
                public const uint Button_5_Button_PressEvent = 1005;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: Main_Page.Pods_List.BtnListPodSelect.Button6ItemPress
                /// Main_Page.Pods_List.Button6.ItemPress
                /// </summary>
                public const uint Button_6_Button_PressEvent = 1006;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: Main_Page.Pods_List.BtnListPodSelect.Button7ItemPress
                /// Main_Page.Pods_List.Button7.ItemPress
                /// </summary>
                public const uint Button_7_Button_PressEvent = 1007;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: Main_Page.Pods_List.BtnListPodSelect.Button8ItemPress
                /// Main_Page.Pods_List.Button8.ItemPress
                /// </summary>
                public const uint Button_8_Button_PressEvent = 1008;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: Main_Page.Pods_List.BtnListPodSelect.Button9ItemPress
                /// Main_Page.Pods_List.Button9.ItemPress
                /// </summary>
                public const uint Button_9_Button_PressEvent = 1009;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: Main_Page.Pods_List.BtnListPodSelect.Button10ItemPress
                /// Main_Page.Pods_List.Button10.ItemPress
                /// </summary>
                public const uint Button_10_Button_PressEvent = 1010;


                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Main_Page.Pods_List.BtnListPodSelect.Button1ItemSelected
                /// Main_Page.Pods_List.Button1.ItemSelected
                /// </summary>
                public const uint Button_1_Button_SelectedState = 1001;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Main_Page.Pods_List.BtnListPodSelect.Button2ItemSelected
                /// Main_Page.Pods_List.Button2.ItemSelected
                /// </summary>
                public const uint Button_2_Button_SelectedState = 1002;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Main_Page.Pods_List.BtnListPodSelect.Button3ItemSelected
                /// Main_Page.Pods_List.Button3.ItemSelected
                /// </summary>
                public const uint Button_3_Button_SelectedState = 1003;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Main_Page.Pods_List.BtnListPodSelect.Button4ItemSelected
                /// Main_Page.Pods_List.Button4.ItemSelected
                /// </summary>
                public const uint Button_4_Button_SelectedState = 1004;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Main_Page.Pods_List.BtnListPodSelect.Button5ItemSelected
                /// Main_Page.Pods_List.Button5.ItemSelected
                /// </summary>
                public const uint Button_5_Button_SelectedState = 1005;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Main_Page.Pods_List.BtnListPodSelect.Button6ItemSelected
                /// Main_Page.Pods_List.Button6.ItemSelected
                /// </summary>
                public const uint Button_6_Button_SelectedState = 1006;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Main_Page.Pods_List.BtnListPodSelect.Button7ItemSelected
                /// Main_Page.Pods_List.Button7.ItemSelected
                /// </summary>
                public const uint Button_7_Button_SelectedState = 1007;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Main_Page.Pods_List.BtnListPodSelect.Button8ItemSelected
                /// Main_Page.Pods_List.Button8.ItemSelected
                /// </summary>
                public const uint Button_8_Button_SelectedState = 1008;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Main_Page.Pods_List.BtnListPodSelect.Button9ItemSelected
                /// Main_Page.Pods_List.Button9.ItemSelected
                /// </summary>
                public const uint Button_9_Button_SelectedState = 1009;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Main_Page.Pods_List.BtnListPodSelect.Button10ItemSelected
                /// Main_Page.Pods_List.Button10.ItemSelected
                /// </summary>
                public const uint Button_10_Button_SelectedState = 1010;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Main_Page.Pods_List.BtnListPodSelect.Button1Visible
                /// Main_Page.Pods_List.Button1.Visible
                /// </summary>
                public const uint Button_1_Button_VisibleState = 1501;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Main_Page.Pods_List.BtnListPodSelect.Button2Visible
                /// Main_Page.Pods_List.Button2.Visible
                /// </summary>
                public const uint Button_2_Button_VisibleState = 1502;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Main_Page.Pods_List.BtnListPodSelect.Button3Visible
                /// Main_Page.Pods_List.Button3.Visible
                /// </summary>
                public const uint Button_3_Button_VisibleState = 1503;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Main_Page.Pods_List.BtnListPodSelect.Button4Visible
                /// Main_Page.Pods_List.Button4.Visible
                /// </summary>
                public const uint Button_4_Button_VisibleState = 1504;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Main_Page.Pods_List.BtnListPodSelect.Button5Visible
                /// Main_Page.Pods_List.Button5.Visible
                /// </summary>
                public const uint Button_5_Button_VisibleState = 1505;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Main_Page.Pods_List.BtnListPodSelect.Button6Visible
                /// Main_Page.Pods_List.Button6.Visible
                /// </summary>
                public const uint Button_6_Button_VisibleState = 1506;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Main_Page.Pods_List.BtnListPodSelect.Button7Visible
                /// Main_Page.Pods_List.Button7.Visible
                /// </summary>
                public const uint Button_7_Button_VisibleState = 1507;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Main_Page.Pods_List.BtnListPodSelect.Button8Visible
                /// Main_Page.Pods_List.Button8.Visible
                /// </summary>
                public const uint Button_8_Button_VisibleState = 1508;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Main_Page.Pods_List.BtnListPodSelect.Button9Visible
                /// Main_Page.Pods_List.Button9.Visible
                /// </summary>
                public const uint Button_9_Button_VisibleState = 1509;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: Main_Page.Pods_List.BtnListPodSelect.Button10Visible
                /// Main_Page.Pods_List.Button10.Visible
                /// </summary>
                public const uint Button_10_Button_VisibleState = 1510;

            }
        }

        #endregion

        #region Construction and Initialization

        /// <summary>
        /// Initializes a new instance of the <see cref="BtnListPodSelect"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        internal BtnListPodSelect(ComponentMediator componentMediator, uint controlJoinId, uint? itemCount)
        {
            ComponentMediator = componentMediator;
            Initialize(controlJoinId, itemCount);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BtnListPodSelect"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        internal BtnListPodSelect(ComponentMediator componentMediator, uint controlJoinId) : this(componentMediator, controlJoinId, null)
        {
        }

        /// <summary>
        /// Initializes a new instance with default itemCount.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        private void Initialize(uint controlJoinId)
        {
            Initialize(controlJoinId, null);
        }

        private Dictionary<string, Indexes> _indexLookup = new Dictionary<string, Indexes>();

        /// <summary>
        /// Initializes a new instance of the <see cref="BtnListPodSelect"/> component class.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        private void Initialize(uint controlJoinId, uint? itemCount)
        {
            ControlJoinId = controlJoinId; 
 
            _devices = new List<BasicTriListWithSmartObject>(); 
 

            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.Button_1_Button_PressEvent, onButton_1_Button_Press);
            ComponentMediator.ConfigureBooleanItemEvent(controlJoinId, Joins.Booleans.Button_1_Button_PressEvent, GetIndexes, onButton_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.Button_2_Button_PressEvent, onButton_2_Button_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.Button_3_Button_PressEvent, onButton_3_Button_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.Button_4_Button_PressEvent, onButton_4_Button_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.Button_5_Button_PressEvent, onButton_5_Button_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.Button_6_Button_PressEvent, onButton_6_Button_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.Button_7_Button_PressEvent, onButton_7_Button_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.Button_8_Button_PressEvent, onButton_8_Button_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.Button_9_Button_PressEvent, onButton_9_Button_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.Button_10_Button_PressEvent, onButton_10_Button_Press);
        }

        /// <summary>
        /// Get the offset when using indexed complex components.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId of the component.</param>
        /// <param name="join">The join offset.</param>
        /// <param name="eSigType">The join data type.</param>
        private Indexes GetIndexes(uint controlJoinId, uint join, eSigType eSigType)
        {
            if (controlJoinId == ControlJoinId &&
                join >= Joins.Booleans.Button_1_Button_PressEvent &&
                join <= 1010)
            {
                return new Indexes(0, (ushort)(join - Joins.Booleans.Button_1_Button_PressEvent), false);
            }

            return new Indexes(0, 0, true);
        }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            Devices.Add(device);
            ComponentMediator.HookSmartObjectEvents(device.SmartObjects[ControlJoinId]);
        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            Devices.Remove(device);
            ComponentMediator.UnHookSmartObjectEvents(device.SmartObjects[ControlJoinId]);
        }

        #endregion

        #region CH5 Contract

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> Button_1_Button_PressEvent;
        private void onButton_1_Button_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = Button_1_Button_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> Button_2_Button_PressEvent;
        private void onButton_2_Button_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = Button_2_Button_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> Button_3_Button_PressEvent;
        private void onButton_3_Button_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = Button_3_Button_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> Button_4_Button_PressEvent;
        private void onButton_4_Button_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = Button_4_Button_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> Button_5_Button_PressEvent;
        private void onButton_5_Button_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = Button_5_Button_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> Button_6_Button_PressEvent;
        private void onButton_6_Button_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = Button_6_Button_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> Button_7_Button_PressEvent;
        private void onButton_7_Button_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = Button_7_Button_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> Button_8_Button_PressEvent;
        private void onButton_8_Button_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = Button_8_Button_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> Button_9_Button_PressEvent;
        private void onButton_9_Button_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = Button_9_Button_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> Button_10_Button_PressEvent;
        private void onButton_10_Button_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = Button_10_Button_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public void Button_1_Button_Selected(BtnListPodSelectBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Button_1_Button_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void Button_1_Button_Selected(bool digital)
        {
            Button_1_Button_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void Button_1_Button_Visible(BtnListPodSelectBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Button_1_Button_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void Button_1_Button_Visible(bool digital)
        {
            Button_1_Button_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void Button_10_Button_Selected(BtnListPodSelectBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Button_10_Button_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void Button_10_Button_Selected(bool digital)
        {
            Button_10_Button_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void Button_10_Button_Visible(BtnListPodSelectBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Button_10_Button_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void Button_10_Button_Visible(bool digital)
        {
            Button_10_Button_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void Button_2_Button_Selected(BtnListPodSelectBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Button_2_Button_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void Button_2_Button_Selected(bool digital)
        {
            Button_2_Button_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void Button_2_Button_Visible(BtnListPodSelectBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Button_2_Button_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void Button_2_Button_Visible(bool digital)
        {
            Button_2_Button_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void Button_3_Button_Selected(BtnListPodSelectBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Button_3_Button_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void Button_3_Button_Selected(bool digital)
        {
            Button_3_Button_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void Button_3_Button_Visible(BtnListPodSelectBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Button_3_Button_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void Button_3_Button_Visible(bool digital)
        {
            Button_3_Button_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void Button_4_Button_Selected(BtnListPodSelectBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Button_4_Button_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void Button_4_Button_Selected(bool digital)
        {
            Button_4_Button_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void Button_4_Button_Visible(BtnListPodSelectBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Button_4_Button_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void Button_4_Button_Visible(bool digital)
        {
            Button_4_Button_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void Button_5_Button_Selected(BtnListPodSelectBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Button_5_Button_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void Button_5_Button_Selected(bool digital)
        {
            Button_5_Button_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void Button_5_Button_Visible(BtnListPodSelectBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Button_5_Button_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void Button_5_Button_Visible(bool digital)
        {
            Button_5_Button_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void Button_6_Button_Selected(BtnListPodSelectBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Button_6_Button_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void Button_6_Button_Selected(bool digital)
        {
            Button_6_Button_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void Button_6_Button_Visible(BtnListPodSelectBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Button_6_Button_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void Button_6_Button_Visible(bool digital)
        {
            Button_6_Button_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void Button_7_Button_Selected(BtnListPodSelectBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Button_7_Button_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void Button_7_Button_Selected(bool digital)
        {
            Button_7_Button_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void Button_7_Button_Visible(BtnListPodSelectBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Button_7_Button_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void Button_7_Button_Visible(bool digital)
        {
            Button_7_Button_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void Button_8_Button_Selected(BtnListPodSelectBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Button_8_Button_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void Button_8_Button_Selected(bool digital)
        {
            Button_8_Button_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void Button_8_Button_Visible(BtnListPodSelectBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Button_8_Button_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void Button_8_Button_Visible(bool digital)
        {
            Button_8_Button_Visible((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void Button_9_Button_Selected(BtnListPodSelectBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Button_9_Button_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void Button_9_Button_Selected(bool digital)
        {
            Button_9_Button_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void Button_9_Button_Visible(BtnListPodSelectBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Button_9_Button_VisibleState], this);
            }
        }

        /// <inheritdoc/>
        public void Button_9_Button_Visible(bool digital)
        {
            Button_9_Button_Visible((sig, component) => sig.BoolValue = digital);
        }

        #endregion

        #region Overrides

        public override int GetHashCode()
        {
            return (int)ControlJoinId;
        }

        public override string ToString()
        {
            return string.Format("Contract: {0} Component: {1} HashCode: {2} {3}", "BtnListPodSelect", GetType().Name, GetHashCode(), UserObject != null ? "UserObject: " + UserObject : null);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

            Button_1_Button_PressEvent = null;
            Button_PressEvent = null;
            Button_2_Button_PressEvent = null;
            Button_3_Button_PressEvent = null;
            Button_4_Button_PressEvent = null;
            Button_5_Button_PressEvent = null;
            Button_6_Button_PressEvent = null;
            Button_7_Button_PressEvent = null;
            Button_8_Button_PressEvent = null;
            Button_9_Button_PressEvent = null;
            Button_10_Button_PressEvent = null;
        }

        #endregion
    }
}
